# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "ğŸ«¡"
error_symbol = "ğŸ˜±"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[deno]
symbol = "ğŸ¦• "

[docker_context]
symbol = "ğŸ³ "

[git_branch]
symbol = "î‚  "

[golang]
symbol = "ğŸ©µ "

[nodejs]
symbol = "ğŸŸ¨ "
version_format = "v${major}"

[python]
symbol = "ğŸ "

[sudo]
symbol = "sudo "

[gcloud]
disabled = true
